syntax = "proto3";

package services;
option go_package = "./services";

import "gender.proto"; 
import "google/protobuf/timestamp.proto";

service Calculator {
    rpc Hello(HelloRequest) returns(HelloResponse);  
    rpc Fibonacci(FibonacciRequest) returns(stream FibonacciResponse); 
    rpc Average(stream AverageRequest) returns(AverageResponse);
}
 

message HelloRequest {
    string name = 1;
    // reserved 1; //จองเลขแท็คไว้ไม่ให้ใช้
    // reserved "name"; //จองชื่อไว้ไม่ให้ใช้
    google.protobuf.Timestamp create_date = 2;
    
}

//PascalCase
message HelloResponse {
    string result = 1; //snack_case
}

message Person {
    string name = 1;
    int32 age = 2;
    float weight = 3;
    double height = 4;
    repeated string phone_number = 5; //slice ของสตริง 
    Gender gender = 7;
    map<string, string> conutries = 8;
    google.protobuf.Timestamp create_date = 9;
}

message FibonacciRequest {
    uint32 n = 1; 
}

message FibonacciResponse {
    uint32 result = 1;
}

message AverageRequest {
    double number = 1;
}
message AverageResponse {
    double result = 1;
}