// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: gender.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// practice
// แบบนี้มีข้อเสีย ถ้าเราอัปเดต proto แต่ client ยังใช้เวอร์ชันเดิมอยู่
// เร้าจะไม่รู้ว่า client เป็นเพศชายจริงไหม
// ใส่ ตัว 0 เป็น UNKNOW
type Gender int32

const (
	Gender_UNKNOW Gender = 0
	Gender_MALE   Gender = 1
	Gender_FEMALE Gender = 2
)

// Enum value maps for Gender.
var (
	Gender_name = map[int32]string{
		0: "UNKNOW",
		1: "MALE",
		2: "FEMALE",
	}
	Gender_value = map[string]int32{
		"UNKNOW": 0,
		"MALE":   1,
		"FEMALE": 2,
	}
)

func (x Gender) Enum() *Gender {
	p := new(Gender)
	*p = x
	return p
}

func (x Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_gender_proto_enumTypes[0].Descriptor()
}

func (Gender) Type() protoreflect.EnumType {
	return &file_gender_proto_enumTypes[0]
}

func (x Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gender.Descriptor instead.
func (Gender) EnumDescriptor() ([]byte, []int) {
	return file_gender_proto_rawDescGZIP(), []int{0}
}

var File_gender_proto protoreflect.FileDescriptor

const file_gender_proto_rawDesc = "" +
	"\n" +
	"\fgender.proto\x12\bservices**\n" +
	"\x06Gender\x12\n" +
	"\n" +
	"\x06UNKNOW\x10\x00\x12\b\n" +
	"\x04MALE\x10\x01\x12\n" +
	"\n" +
	"\x06FEMALE\x10\x02B\fZ\n" +
	"./servicesb\x06proto3"

var (
	file_gender_proto_rawDescOnce sync.Once
	file_gender_proto_rawDescData []byte
)

func file_gender_proto_rawDescGZIP() []byte {
	file_gender_proto_rawDescOnce.Do(func() {
		file_gender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gender_proto_rawDesc), len(file_gender_proto_rawDesc)))
	})
	return file_gender_proto_rawDescData
}

var file_gender_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gender_proto_goTypes = []any{
	(Gender)(0), // 0: services.Gender
}
var file_gender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gender_proto_init() }
func file_gender_proto_init() {
	if File_gender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gender_proto_rawDesc), len(file_gender_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gender_proto_goTypes,
		DependencyIndexes: file_gender_proto_depIdxs,
		EnumInfos:         file_gender_proto_enumTypes,
	}.Build()
	File_gender_proto = out.File
	file_gender_proto_goTypes = nil
	file_gender_proto_depIdxs = nil
}
